### ISSUE TITLE
Transient/Many to Many relationships?

### ISSUE THREAD

**Issue by ducharmemp** [davidpdrsn/diesel-factories#17]
Hi! Fantastic library, it really has helped me write dummy data for my test cases and it's been remarkably straightforward since I was originally using a hacked together python script to seed the database. I understand that this lib mainly deals with `belongs_to` associations, is there a way to extend this to include `has_many` through a join table? I know diesel itself doesn't deal with this so it's probably very difficult if not outright impossible. My initial thought was that I could somehow grab a connection to the db on a `Factory::default` call, but that seems outside of the scope of a default constructor. Some way of defining `after(conn: &Connection)` or `before(conn: &Connection)` for the insert would probably be enough I think?

**Comment by davidpdrsn** [comment]
Thanks. I'm glad you're getting use out of it.

I haven't dealt much with many to many relationships in Diesel but it is a common thing so it would be cool if diesel-factories made them easy to setup. I haven't touched the code in a while and have actually been thinking about doing a rewrite. Especially the code generation could use some love. 

You're welcome to attempt this in a PR otherwise I'll try and look into it. Can't say when that will be however.

**Comment by ducharmemp** [comment]
I'll try to take a look and see what I can do, maybe something with associations or a different trait?

**Comment by davidpdrsn** [comment]
Not sure 😅

**Comment by davidpdrsn** [comment]
I'll go head a close this. People are welcome to experiment and submit PRs but I wont be exploring this for now.
